"""Core interfaces for GradSCF.

This package re-exports a large surface area. Keep the re-exports lazy so
submodule imports do not pull the entire stack into memory during process
startup.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_NAMESPACE_EXPORTS = {
    "solvers",
    "ci",
    "integrals",
    "gto",
    "scf",
    "dft",
    "tdscf",
    "tddft",
    "model",
    "tools",
    "workflows",
    "data",
    "df",
}

_PUBLIC_EXPORTS = {
    "BoundNeuralXCFunctional": "model.neural_xc",
    "BoundXCFunctionalProtocol": "tools.protocols",
    "CLASSIC_XC_SPECS": "dft",
    "CartesianAO": "data",
    "CartesianBasis": "data",
    "DifferentiableSCF": "scf",
    "DifferentiableSCFConfig": "scf",
    "DifferentiableSCFInfo": "scf",
    "DispersionCorrectedFunctional": "model.neural_d",
    "DispersionFunctional": "model.neural_d",
    "ExperimentConfig": "workflows",
    "ExperimentPipeline": "workflows",
    "ExperimentRun": "workflows",
    "Functional": "model.neural_xc",
    "GradDFTDispersionNetwork": "model.neural_d",
    "ResidualMixingMLP": "model.neural_xc",
    "QuadratureGrid": "scf",
    "MolecularTrainingDatum": "model.training",
    "GroundStateReference": "tools.types",
    "MolecularTrainingConfig": "model.training",
    "HARTREE_TO_EV": "tools.spectra",
    "MissingDependencyError": "tools.upstreams",
    "MoleculeConfig": "tools.api",
    "MoleculeRun": "workflows",
    "MoleculeSpecConfig": "workflows",
    "MoleculeReferenceProtocol": "tools.protocols",
    "NeuralExcitedStateRun": "workflows",
    "NeuralXCHybridFunctional": "model.neural_xc",
    "NeuralXCMixingMLP": "model.neural_xc",
    "NeuralXCTrainingConfig": "workflows",
    "OutputConfig": "workflows",
    "OutputPaths": "workflows",
    "PipelineRun": "workflows",
    "RHFConfig": "scf",
    "RHFResult": "scf",
    "RKSConfig": "scf",
    "RKSResult": "scf",
    "RestrictedCasidaTDDFT": "tddft",
    "RestrictedFeatureBundle": "dft.libxc_jax.jax_libxc",
    "RestrictedMolecule": "scf",
    "SimulationConfig": "workflows",
    "SpectrumGridConfig": "workflows",
    "SpectrumRun": "workflows",
    "SystemConfig": "workflows",
    "TDAResult": "tddft",
    "TDDFTResult": "tddft",
    "TraditionalXCFunctional": "dft",
    "TrainingRun": "workflows",
    "UKSConfig": "scf",
    "UKSResult": "scf",
    "UnrestrictedCasidaTDDFT": "tddft",
    "UnrestrictedMolecule": "scf",
    "UnrestrictedTDA": "tddft",
    "UnrestrictedTDAResult": "tddft",
    "UnrestrictedTDDFTResult": "tddft",
    "XCFunctionalProtocol": "tools.protocols",
    "b3lyp_component_basis": "dft.libxc_jax.jax_libxc",
    "b3lyp_component_coefficients": "dft.libxc_jax.jax_libxc",
    "benzene_experiment_config": "workflows",
    "benzene_strict_jax_experiment_config": "workflows",
    "build_hcore": "integrals",
    "build_jk_from_df": "df",
    "build_molecule": "tools.api",
    "build_dispersion_pair_inputs": "model.neural_d",
    "cartesian_angular_tuples": "data",
    "calculate_distances": "model.neural_d",
    "create_train_state": "model.training",
    "create_train_state_from_molecule": "model.training",
    "density_matching_penalty": "model.training",
    "density_on_grid": "model.training",
    "density_on_grid_spin_resolved": "model.training",
    "eri_element": "integrals",
    "eri_tensor": "integrals",
    "eri_tensor_screened": "integrals",
    "eri_to_df_factors": "df",
    "eval_xc_energy_density": "dft.libxc_jax.jax_libxc",
    "evaluate_cartesian_ao": "data",
    "gen_tda_vind": "tddft",
    "gen_tdhf_vind": "tddft",
    "ground_state_from_grad_dft_molecule": "tools.upstreams",
    "molecular_loss": "model.training",
    "has_grad_dft": "tools.upstreams",
    "has_jax_xc": "tools.upstreams",
    "hybrid_coeff": "dft.libxc_jax.jax_libxc",
    "kinetic_element": "integrals",
    "kinetic_matrix": "integrals",
    "load_jax_xc": "dft.libxc_jax.jax_xc_adapter",
    "lorentzian_spectrum": "tools.spectra",
    "make_b3lyp_functional": "dft",
    "make_classic_xc_functional": "dft",
    "make_dispersion_corrected_functional": "model.neural_d",
    "make_fixed_density_predictor": "model.training",
    "make_functional": "model.neural_xc",
    "make_ground_state_predictor": "model.training",
    "make_molecular_eval": "model.training",
    "make_molecular_loss_and_grad": "model.training",
    "make_molecular_train_step": "model.training",
    "make_lda_functional": "dft",
    "make_neural_xc_functional": "model.neural_xc",
    "make_neural_d_functional": "model.neural_d",
    "make_pbe0_functional": "dft",
    "make_pbe_functional": "dft",
    "make_self_consistent_predictor": "model.training",
    "nuclear_attraction_element": "integrals",
    "nuclear_attraction_matrix": "integrals",
    "nuclear_repulsion_energy": "scf",
    "oscillator_strengths": "tools.spectra",
    "overlap_element": "integrals",
    "overlap_matrix": "integrals",
    "parse_xc": "dft.libxc_jax.jax_libxc",
    "predict_excitation_energies": "model.training",
    "predict_excitation_spectrum": "model.training",
    "predict_ground_state_density": "model.training",
    "predict_ground_state_molecule": "model.training",
    "predict_ground_state_total_energy": "model.training",
    "put_molecule_on_device": "tools.device",
    "put_restricted_molecule_on_device": "tools.device",
    "resolve_coefficient_prior_values": "model.neural_xc",
    "resolve_execution_device": "tools.device",
    "restricted_grid_features": "tools.features",
    "restricted_molecule_from_spec_with_jax_rks": "scf",
    "unrestricted_molecule_from_spec_with_jax_uks": "scf",
    "run_and_report": "workflows",
    "run_and_report_from_spec": "workflows",
    "run_experiment": "workflows",
    "run_molecule_from_spec": "workflows",
    "run_neural_xc_spectrum_pipeline": "workflows",
    "run_neural_xc_spectrum_pipeline_from_molecule_spec": "workflows",
    "run_neural_xc_spectrum_pipeline_from_spec": "workflows",
    "run_pipeline": "tools.api",
    "run_pipeline_core_from_molecule_spec": "workflows",
    "run_pipeline_core_from_spec": "workflows",
    "run_rhf": "scf",
    "run_rhf_from_integrals": "scf",
    "run_rks_from_integrals": "scf",
    "run_spectrum_pipeline": "tools.api",
    "run_uks_from_integrals": "scf",
    "scale_restricted_grid_features": "tools.features",
    "schwarz_bounds": "integrals",
    "semilocal_terms": "dft.libxc_jax.jax_libxc",
    "spin_summed_density_matrix": "tools.upstreams",
    "transition_dipoles": "tools.spectra",
    "water_experiment_config": "workflows",
    "water_strict_jax_experiment_config": "workflows",
    "xc_type": "dft.libxc_jax.jax_libxc",
}

__all__ = sorted(_NAMESPACE_EXPORTS) + list(_PUBLIC_EXPORTS)


def __getattr__(name: str) -> Any:
    if name in _NAMESPACE_EXPORTS:
        module = import_module(f".{name}", __name__)
        globals()[name] = module
        return module
    if name not in _PUBLIC_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{_PUBLIC_EXPORTS[name]}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
