"""Matrix-free non-Hermitian Ritz solves and isolated energy response."""

import jax
import jax.numpy as jnp
import numpy as np
import pytest
from gradscf.solvers import LinearOperator, NonHermitianSolverConfig, solve_nonhermitian


def problem(n=60):
    rng = np.random.default_rng(12)
    diagonal = np.linspace(0.4, 8.0, n)
    s = np.eye(n) + 0.018 * rng.normal(size=(n, n))
    a = s @ np.diag(diagonal) @ np.linalg.inv(s)
    b = rng.normal(size=(n, n)) * 0.015
    return jnp.asarray(a), jnp.asarray(b), diagonal


def test_restarted_pairs_and_jit_energy_derivatives():
    a, b, expected = problem()
    cfg = NonHermitianSolverConfig(
        method="davidson", nroots=2, max_space=20, maxiter=150, atol=1e-9
    )

    def solve(t):
        matrix = a + t * b
        op = LinearOperator(
            a.shape,
            a.dtype,
            lambda v: matrix @ v,
            diagonal=jnp.diag(matrix),
            transpose_matvec=lambda v: matrix.T @ v,
        )
        return solve_nonhermitian(op, config=cfg)

    out = jax.jit(solve)(0.0)
    assert np.all(out.converged & out.response_valid)
    assert not out.spectrum_complete
    assert out.restarts > 0
    assert out.iterations > 1
    assert out.subspace_dimension <= cfg.max_space
    np.testing.assert_allclose(out.values, expected[:2], atol=2e-9, rtol=0)
    np.testing.assert_allclose(
        out.left_vectors.T @ out.right_vectors, np.eye(2), atol=1e-10
    )
    f = lambda t: jnp.sum(solve(t).values)
    ad = jax.jit(jax.grad(f))(0.0)
    dense = lambda t: jnp.sum(
        solve_nonhermitian(a + t * b, config=NonHermitianSolverConfig(nroots=2)).values
    )
    np.testing.assert_allclose(ad, jax.grad(dense)(0.0), atol=2e-8, rtol=0)
    np.testing.assert_allclose(jax.jvp(f, (0.0,), (1.0,))[1], ad, atol=1e-10)
    np.testing.assert_allclose(ad, (f(1e-4) - f(-1e-4)) / 2e-4, atol=2e-7)


def test_large_operator_bypasses_dense_limit_without_wide_probes():
    n = 300
    d = jnp.linspace(-0.3, 5.0, n)
    widths = []

    def apply(v):
        if v.ndim == 2:
            widths.append(v.shape[1])
            assert v.shape[1] <= 24
        return d.reshape((n,) + (1,) * (v.ndim - 1)) * v

    op = LinearOperator(
        (n, n), d.dtype, apply, diagonal=d, matmat=apply, transpose_matvec=apply
    )
    cfg = NonHermitianSolverConfig(
        method="davidson", max_dense=4, max_space=24, atol=1e-10
    )
    out = jax.jit(lambda: solve_nonhermitian(op, config=cfg))()
    assert out.converged[0] and out.response_valid[0]
    np.testing.assert_allclose(out.values, [-0.3], atol=1e-11)
    assert max(widths) <= 24
    assert not out.spectrum_complete


def test_failed_iteration_has_invalid_response():
    a, b, _ = problem()
    cfg = NonHermitianSolverConfig(
        method="davidson", max_space=16, maxiter=1, atol=1e-12
    )
    f = lambda t: solve_nonhermitian(a + t * b, config=cfg)
    assert not np.all(f(0.0).converged)
    assert not np.any(f(0.0).response_valid)
    assert not np.isfinite(jax.grad(lambda t: f(t).values[0])(0.0))


@pytest.mark.parametrize(
    "a", [jnp.diag(jnp.array([1.0, 1.0, 3.0])), jnp.array([[0.0, -1.0], [1.0, 0.0]])]
)
def test_full_space_degenerate_or_complex_roots_remain_invalid(a):
    cfg = NonHermitianSolverConfig(method="davidson", max_space=12)
    out = solve_nonhermitian(a, config=cfg)
    assert out.spectrum_complete
    assert not np.any(out.response_valid)
    assert not np.isfinite(
        jax.grad(lambda t: solve_nonhermitian(a * t, config=cfg).values[0])(1.0)
    )


def test_forward_reverse_jaxprs_have_no_physical_dense_matrix():
    n = 160
    d = jnp.linspace(0.5, 7.0, n)
    cfg = NonHermitianSolverConfig(method="davidson", max_space=16, max_dense=2)

    def energy(t):
        # A nonsymmetric bidiagonal action; its transpose is generated by JAX.
        def apply(v):
            return d * v + t * jnp.concatenate([v[1:], jnp.zeros(1)])

        op = LinearOperator((n, n), d.dtype, apply, diagonal=d)
        return solve_nonhermitian(op, config=cfg).values[0]

    def check(jaxpr):
        if hasattr(jaxpr, "jaxpr"):
            check(jaxpr.jaxpr)
        elif hasattr(jaxpr, "eqns"):
            for eq in jaxpr.eqns:
                for variable in (*eq.invars, *eq.outvars):
                    assert getattr(getattr(variable, "aval", None), "shape", None) != (
                        n,
                        n,
                    )
                for value in eq.params.values():
                    check(value)
        elif isinstance(jaxpr, (tuple, list)):
            for value in jaxpr:
                check(value)
        elif isinstance(jaxpr, dict):
            for value in jaxpr.values():
                check(value)

    check(jax.make_jaxpr(energy)(0.1))
    check(jax.make_jaxpr(jax.grad(energy))(0.1))
    assert np.isfinite(jax.jit(jax.grad(energy))(0.1))


def test_repeated_restarts_without_diagonal_and_initial_guesses():
    a, _, expected = problem(48)
    op = LinearOperator(a.shape, a.dtype, lambda v: a @ v)
    cfg = NonHermitianSolverConfig(
        method="davidson", nroots=2, max_space=20, maxiter=150
    )
    out = solve_nonhermitian(op, config=cfg, initial_vectors=jnp.eye(48)[:, -2:])
    assert np.all(out.response_valid)
    np.testing.assert_allclose(out.values, expected[:2], atol=2e-9)
    assert out.iterations > 2


def test_failed_guard_invalidates_convergence_even_for_exact_requested_root():
    rng = np.random.default_rng(9)
    a = np.zeros((30, 30))
    a[0, 0] = -1.0
    a[1:, 1:] = np.diag(np.linspace(1.0, 9.0, 29)) + 0.1 * rng.normal(size=(29, 29))
    cfg = NonHermitianSolverConfig(method="davidson", maxiter=1, max_space=16)
    out = solve_nonhermitian(
        jnp.asarray(a), config=cfg, initial_vectors=jnp.eye(30)[:, :2]
    )
    assert out.residual_norms[0] < 1e-12
    assert out.guard_residual_norms[0] > 1e-3
    assert not np.any(out.converged | out.response_valid)


def test_full_support_guesses_find_a_lower_disconnected_nonnormal_block():
    a = jnp.diag(jnp.linspace(-0.5, 5.0, 40))
    a = a.at[-2:, -2:].set(jnp.array([[3.0, 8.0], [2.0, 3.0]]))
    options = NonHermitianSolverConfig(method="davidson", max_space=16, maxiter=150)
    out = solve_nonhermitian(a, config=options)
    assert out.response_valid[0]
    np.testing.assert_allclose(out.values, [-1.0], atol=2e-9)


def test_iterative_configuration_guards():
    from gradscf.cc.eom import EOMConfig

    assert NonHermitianSolverConfig(2).nroots == 2
    assert EOMConfig("ip", 2, "dense", 1e-10).conv_tol == 1e-10
    with pytest.raises(ValueError, match="max_space"):
        solve_nonhermitian(
            jnp.eye(40), config=NonHermitianSolverConfig(method="davidson", max_space=4)
        )
    for kwargs in (
        {"guard_roots": 0},
        {"maxiter": 0},
        {"seed": -1},
        {"method": "arnoldi"},
        {"preconditioner_floor": 0.0},
    ):
        with pytest.raises(ValueError):
            NonHermitianSolverConfig(**kwargs)
    with pytest.raises(ValueError, match="initial_vectors"):
        solve_nonhermitian(
            jnp.eye(4),
            config=NonHermitianSolverConfig(method="davidson"),
            initial_vectors=jnp.ones((5, 2)),
        )
