"""Train a smooth neural KEDF correction through the converged OFDFT density.

A tiny pure-JAX MLP illustrates the same init/apply + external parameters
pattern as neural XC. A Flax model.apply callback can replace this network.
The target here is generated by another network, not ab-initio reference data.
All numbers use atomic units; XC is explicitly disabled.
"""
from dataclasses import replace
import jax
import jax.numpy as jnp
import optax

jax.config.update('jax_enable_x64', True)

from gradscf import ofdft


def correction(network, features):
    hidden = jnp.tanh(features.rho[:,None]*network['w']+network['b'])
    return jnp.sum(features.weights*features.rho*(hidden@network['out']))


functional = ofdft.NeuralKineticFunctional(correction)
data = ofdft.periodic_inputs(jnp.eye(3)*5., (3,3,3), nelectron=2.)
mode = jnp.cos(2*jnp.pi*data.coordinates[:,0]/5.)
data = replace(data, external_potential=.1*mode)
config = ofdft.OFDFTConfig(xc=None, tolerance=1e-9)
params = {'network': {'w': jnp.array([.4,-.2]), 'b': jnp.array([.1,.3]),
                      'out': jnp.array([.7,.4])}}
teacher = {'network': {**params['network'], 'w': jnp.array([1.,-.5])}}


def density(params):
    return ofdft.run_ofdft(data, kinetic=functional, kinetic_params=params, config=config).density


target = jax.lax.stop_gradient(density(teacher))

def loss(params):
    return jnp.sum(data.weights*(density(params)-target)**2)/jnp.sum(data.weights*target**2)


value_grad = jax.jit(jax.value_and_grad(loss))
optimizer = optax.adam(.02)
state = optimizer.init(params)
initial_loss = float(loss(params))
for step in range(8):
    value, gradients = value_grad(params)
    if not all(bool(jnp.all(jnp.isfinite(x))) for x in jax.tree.leaves(gradients)):
        raise RuntimeError('Forward stationarity or implicit response failed')
    updates, state = optimizer.update(gradients,state,params)
    params = optax.apply_updates(params,updates)
    print('step',step,'density loss:',float(value))
final_loss = float(loss(params))
print('Initial/final loss:',initial_loss,final_loss)
assert final_loss < initial_loss

# CPU float64 output: initial loss 1.2825003041211855e-06,
# final loss after 8 Adam updates 2.92350431760668e-08.
